# Generated by Django 4.2.7 on 2025-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.CharField(max_length=45)),
                ('dst_ip', models.CharField(max_length=45)),
                ('protocol', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Suspicious', 'Suspicious'), ('Attack', 'Attack')], max_length=20)),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('involves_local_pc', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
