# Generated by Django 4.2.7 on 2025-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='dst_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='src_port',
            field=models.IntegerField(default=0),
        ),
    ]
